server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider-zx
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.172.227:8848  #nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'
