server:
  port: 9012


spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.172.227:8848  #配置的Nacos地址（本机的写localhost:8848，服务器的写IP地址）


management:
  endpoints:
    web:
      exposure:
        include: '*'
