server:
  port: 84

spring:
  application:
    name: nacos-order-consumer-zx
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.172.227:8848  #nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080    #sentinel
        port: 8719

#消费者将去访问的微服务名称
server-url:
  nacos-user-service: http://nacos-payment-provider-zx

#激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true
